export const FETCH_USER_TIMELINE_SUCCEEDED = 'FETCH_USER_TIMELINE_SUCCEEDED';
export const FETCH_USER_TIMELINE_FAILED = 'FETCH_USER_TIMELINE_FAILED';
export const FETCH_USER_TIMELINE_LOADING = 'FETCH_USER_TIMELINE_LOADING';