export const FETCH_USER_TIMELINE_SUCCEEDED = 'FETCH_USER_TIMELINE_SUCCEEDED';
export const FETCH_USER_TIMELINE_FAILED = 'FETCH_USER_TIMELINE_FAILED';
export const FETCH_USER_TIMELINE_LOADING = 'FETCH_USER_TIMELINE_LOADING';

export const ADD_POST_SUCCEEDED = 'ADD_POST_SECCEEDED';
export const ADD_POST_LOADING = 'ADD_POST_LOADING';
export const ADD_POST_FAILED = 'ADD_POST_FAILED';
export const ADD_POST_COMPLETE = 'ADD_POST_COMPLETE';